<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FraudDetection.ML-aed1f83c-3802-4353-82f7-ba6cb8eddaae</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!-- Core Dependencies -->
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />

	  <!-- ML.NET Dependencies -->
	  <PackageReference Include="Microsoft.ML" Version="3.0.1" />
	  <PackageReference Include="Microsoft.ML.AutoML" Version="0.21.1" />

	  <!-- Database Dependencies -->
	  <PackageReference Include="ClickHouse.Client" Version="6.8.0" />
	  <PackageReference Include="Dapper" Version="2.1.28" />

	  <!-- Logging Dependencies -->
	  <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
	  <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
	  <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
	  <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
	  <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />

	  <!-- Web API Dependencies -->
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />

	  <!-- OpenTelemetry Dependencies -->
	  <PackageReference Include="OpenTelemetry" Version="1.7.0" />
	  <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.7.0" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.7.1" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.7.1" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.7.0" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="0.5.0-beta.4" />
	  <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.7.0" />
	  <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="2.0.0" />

  </ItemGroup>
</Project>
