version: "3.7"

services:
  fraud-detection-ml-prod:
    # volumes:
      # - /opt/appdynamics/dotnet:/opt/appdynamics/dotnet
      # - /nfs/service/microservices:/root
    environment:
      CORECLR_PROFILER: "${CORECLR_PROFILER}"
      CORECLR_ENABLE_PROFILING: "${CORECLR_ENABLE_PROFILING}"
      CORECLR_PROFILER_PATH: "${CORECLR_PROFILER_PATH}"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "${APPDYNAMICS_CONTROLLER_HOST_NAME}"
      APPDYNAMICS_CONTROLLER_PORT: "${APPDYNAMICS_CONTROLLER_PORT}"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "${APPDYNAMICS_AGENT_ACCOUNT_NAME}"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "${APPDYNAMICS_AGENT_APPLICATION_NAME}"
      APPDYNAMICS_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_AGENT_TIER_NAME: "${APPDYNAMICS_AGENT_TIER_NAME}"
      APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX: "${APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX}"
      OTL_INSTANCE_ID: "${IMAGE_TAG}-{{.Task.Slot}}"
      ASPNETCORE_ENVIRONMENT: "Production"
    image: "nexus.beelab.uz:8082/beepul-afs/fraud-detection-ml:${IMAGE_TAG}"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - beepul-afs-prod
      - publish-https
    configs:
      - source: settings_source
        target: "/settings.json"
    secrets:
      - source: secrets_source
        target: secrets.json
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints:
          - node.role == worker
      labels:
        caddy: detection.service-prod.afs.beelab.uz
        caddy.reverse_proxy: "{{ upstreams 80 }}"
        caddy.tls: "/run/secrets/server.crt /run/secrets/server.key"
      resources:
        limits:
          memory: 512Mi
          cpus: "0.5"
  
  fraud-detection-background:
    environment:
      OTL_INSTANCE_ID: "${IMAGE_TAG}-{{.Task.Slot}}"
      ASPNETCORE_ENVIRONMENT: "Production"
    image: "nexus.beelab.uz:8082/beepul-afs/fraud-detection:${IMAGE_TAG}"
    configs:
      - source: settings_source
        target: "/settings.json"
    secrets:
      - source: secrets_source
        target: secrets.json
    command: ["--hangfire"]
    networks:
      - publish-https
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==worker

networks:
  beepul-afs-prod:
    external: true
  publish-https:
    external: true

configs:
  settings_source:
    external: true
    name: "${SETTINGS_NAME}"

secrets:
  secrets_source:
    external: true
    name: "${SECRETS_NAME}"
